<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<div class="z_about_table_1">
		<div class="z_about_table_tdgap"></div>
		<div class="z_about_table_td0a">Hacker. War. Games. Score.</div>
		<div class="z_about_table_tdgap"></div>
</div>

<div class="z_bugnet_table_0">


<table id="grida" class="tablesorter">
<thead>
	<tr>
		<th>Name</th>
		<th>Since</th>
		<th>Points</th>
	</tr>
</thead>
<tbody>
<?php
		$members = $this->warMembers("all");
		foreach ($members as $member) {
			echo "<tr>";
			echo "<td><a href=\"/profile/member/?stdin=". $member["id"] ."\">". $member["handle"] ."</a></td>";
			echo "<td>". $member["since"] ."</td>";
			echo "<td>". $member["points"] ."</td>";
			echo "</tr>\n";
		}
?>
</table>

</div>

<div style="height:25px;width:725px;"></div>

</center>
