<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<div class="z_bugnet_table_0">

<table id="grida" class="tablesorter">
<thead>
	<tr>
		<th>Webpage</th>
		<th>Total</th>
		<th>Since</th>
	</tr>
</thead>
<tbody>
<?php
		$resultB = $this->logsList("links");
		foreach ($resultB as $result) {
?>
	<tr><td>http://<?php echo $result["site"]; ?>/<?php echo $result["controller"]; ?>/<?php echo $result["view"]; ?></td><td><?php echo $result["hits"]; ?></td><td><?php echo $result["created"]; ?></td></tr>
<?php
		}
?>
</tbody>
</table>

</div>

<div style="height:25px;width:725px;"></div>

</center>
