<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<form action="/account/submitintr" method="POST">
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Add Interest</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Name (ie: Robotics):</td>
					<td><input type="text" name="s_name" class="s_account_form_input0" /></td>
				</tr>
				<tr>
					<td>Years Exp (ie: 8 months or 8 years since obtained)</td>
					<td><input type="text" name="s_exp" class="s_account_form_input0" /></td>
				</tr>
				<tr>
					<td>Extra details (ie: specify misc, clubs, etc)</td>
					<td><input type="text" name="s_other" class="s_account_form_input0" /></td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" name="submit" value="Add" class="s_account_form_submit0"></td>
				</tr>
			</tbody>
		</table>
	</div>
</form>
</center>