<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_account_table_0">
<form action="/account/submitskill" method="POST">
	<div class="s_account_table_td0c">Name (ie: Python):</div>
	<div class="s_account_table_td0d"><input type="text" name="s_name" class="s_account_form_input0" /></div>
	<div class="s_account_table_td0c">Years Exp (ie: 8 months or 8 years):</div>
	<div class="s_account_table_td0d"><input type="text" name="s_exp" class="s_account_form_input0" /></div>
	<div class="s_account_table_tr0b"><input type="submit" name="submit" value="Add" class="s_account_form_submit0"></div>
</form>
</div>
