<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');


?>

<div class="my_table_1">

<?php
	if ($this->w0rm == "YAY") {
?>
	<div class="my_header">Success!</div>
		<div class="my_gap"></div>
	<div class="my_header_text">Your handle has now been updated.</div>
<?php
	} else {

?>
	<div class="my_header">Failed!</div>
		<div class="my_gap"></div>
	<div class="my_header_text">Duplicate handle or Invalid handle. Try again.</div>

<?php } ?>
</div>
