<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_account_table_1">
<form action="/account/passwordsubmit" method="POST">
	<div class="s_account_table_td1a">Password:</div>
	<div class="s_account_table_td1b"><input type="password" name="pass1" class="s_account_form_input1" /></div>
	<div class="s_account_table_td1c">Password (again):</div>
	<div class="s_account_table_td1d"><input type="password" name="pass2" class="s_account_form_input1" /></div>
	<div class="s_account_table_tr1a">Regular password changing is a very healthy habit to have.</div>
	<div class="s_account_table_tr1b"><input type="submit" name="submit" value="Change" class="s_account_form_submit1"></div>
</form>
</div>