<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<form action="/account/submitpassword" method="POST">
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Change Password</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Password</td>
					<td><input type="password" name="pass1" class="s_account_form_input1" /></td>
				</tr>
				<tr>
					<td>Password (again)</td>
					<td><input type="password" name="pass2" class="s_account_form_input1" /></td>
				</tr>
				<tr>
					<td colspan="2">Regular password changing is a very healthy habit to have.</td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" name="submit" value="Change" class="s_account_form_submit0"></td>
				</tr>
			</tbody>
		</table>
	</div>
</form>
</center>