<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="b_title">PROFILE</div>
			<div class="b_text">Handle: <?php echo $this->zempirian->handle; ?> <input type="button" value="change"></div>
			<div class="b_text">Password: ******** <input type="button" value="change"></div>
			<div class="b_text">Rights: <?php echo $this->rightsLookup('w0rm'); ?></div>
			<div class="b_text">Since: <?php echo $this->zempirian->since; ?></div>
			<div class="b_text">Email: <?php echo $this->zempirian->email; ?></div>
			<div class="b_text">Points: <?php echo $this->zempirian->points; ?></div>
		</div>
	</div>
</center>