<center>
<form action="/shield/auth" method="POST">
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Shield => Sign in</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>USERNAME</td>
					<td><input type="text" name="username" class="s_shield_form_input2"></td>
				</tr>
				<tr>
					<td>PASSWORD</td>
					<td><input type="password" name="password" class="s_shield_form_input2"></td>
				</tr>
				<tr>
					<td colspan=2>Failed attempt forces a timed ban. Type carefully.</td>
				</tr>
				<tr>
					<td colspan=2>Don't have an account? <a href="/shield/register">Sign up here</a>.</td>
				</tr>
				<tr>
					<td colspan=2><input type="submit" name="submit" value="Sign in" class="s_shield_form_submit2"></td>
				</tr>
			</tbody>
		</table>
	</div>
</form>
</center>