
<div id="dialog">
<div class="s_shield_table_2">
<form action="/shield/auth" method="POST">
	<div class="s_shield_table_td2a">USERNAME</div>
	<div class="s_shield_table_td2b"><input type="text" name="username" class="s_shield_form_input2"></div>
	<div class="s_shield_table_td2c">PASSWORD</div>
	<div class="s_shield_table_td2d"><input type="password" name="password" class="s_shield_form_input2"></div>
	<div class="s_shield_table_tr2a">Failed attempt forces a timed ban. Type carefully.</div>
	<div class="s_shield_table_tr2b">Don't have an account? <a href="/shield/register">Sign up here</a>.</div>
	<div class="s_shield_table_tr2c"><input type="submit" name="submit" value="Login" class="s_shield_form_submit2"></div>
</form>
</div>
</div>