<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>
<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th>Shield => Logout</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Session has been successfully destroyed.</td>
				</tr>
				<tr>
					<td><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-logout.png" border="0"></td>
				</tr>
			</tbody>
		</table>
	</div>
</center>