<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th>Shield => Deny registration</th>
				</tr>
			</thead>
			<tbody>
<?php
	if ($this->w0rm == "YAY") {
?>
				<tr>
					<td>SUCCESS! ACCOUNT WAS DESTROYED</td>
				</tr>
				<tr>
					<td>You have been eliminated from our database.</td>
				</tr>
<?php
	} else {

?>
				<tr>
					<td>There is no code and email matching specified entries.</td>
				</tr>
<?php } ?>
			</tbody>
		</table>
	</div>
</center>