<div class="my_table_1">

<?php
	if ($this->w0rm == "YAY") {
?>
	<div class="s_forum_table_2">
		<div class="s_shield_header">SUCCESS! ACCOUNT WAS DESTROYED</div>
		<div class="s_shield_header_text">You have been eliminated from our database.</div>
	</div>
<?php
	} else {

?>
	<div class="s_forum_table_2">
		<div class="s_shield_header">There is no code and email matching specified entries.</div>
	</div>
<?php } ?>
</div>
