<div class="s_shield_table_5">
<form action="/shield/ngo" method="POST">
			<div class="s_shield_table_tr5a">Please type the email address you received this message from and click delete.</div>
			<div class="s_shield_table_td5a">CODE:</div>
			<div class="s_shield_table_td5b"><input type="text" name="code" value="<?php echo $this->code; ?>" class="s_shield_form_input5"></div>
			<div class="s_shield_table_td5c">EMAIL:</div>
			<div class="s_shield_table_td5d"><input type="text" name="email" class="s_shield_form_input5"></div>
			<div class="s_shield_table_td5e"><input type="submit" name="submit" value="Delete" class="s_shield_form_submit5"></div>
</form>
</div>