<center>
<form action="/shield/create" method="POST">
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Shield => Registration form</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>EMAIL</td>
					<td><input type="text" name="email" class="s_shield_form_input3"></td>
				</tr>
				<tr>
					<td>EMAIL (again)</td>
					<td><input type="text" name="again" class="s_shield_form_input3"></td>
				</tr>
				<tr>
					<td colspan="2">You will receive an email with further instructions.</td>
				</tr>
				<tr>
					<td colspan="2">Already have an account? <a href="/shield/login">Sign in here</a>.</td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" name="submit" value="Create" class="s_shield_form_submit3"></td>
				</tr>
			</tbody>
		</table>
	</div>
</form>
</center>