
<div class="s_shield_table_3">
<form action="/shield/create" method="POST">
	<div class="s_shield_table_td3a">EMAIL</div>
	<div class="s_shield_table_td3b"><input type="text" name="email" class="s_shield_form_input3"></div>
	<div class="s_shield_table_td3c">EMAIL (again)</div>
	<div class="s_shield_table_td3d"><input type="text" name="again" class="s_shield_form_input3"></div>
	<div class="s_shield_table_tr3a">You will receive an email with further instructions.</div>
	<div class="s_shield_table_tr3b">Already have an account? <a href="/shield/login">Sign in here</a>.</div>
	<div class="s_shield_table_tr3c"><input type="submit" name="submit" value="Create" class="s_shield_form_submit3"></div>
</form>
</div>
