<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th>Shield => Registration => Thank you</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Thank you for your request. You will receive further instructions by email. Follow them to gain access to the Academy.</td>
				</tr>
				<tr>
					<td>*** NOTE: Sometimes the email will end up being shoved in to your spam/junk folder.</td>
				</tr>
			</tbody>
		</table>
	</div>
</center>