<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th>Shield => Time banned</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>You have attempted to repeat the same query to fast which has triggered a 300 second cool down.</td>
				</tr>
				<tr>
					<td><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-timeban.png" border="0"></td>
				</tr>
				<tr>
					<td>Wish to remove restrictions? <a href="/donate/help">Upgrade now.</a></td>
				</tr>
			</tbody>
		</table>
	</div>
</center>