<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>
<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th>Shield => Trapped</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>You should not be seeing this. If you are then shame on you.</td>
				</tr>
				<tr>
					<td><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-trap.png"></td>
				</tr>
				<tr>
					<td>Wish to prevent errors? Then don't repeat the mistake.</td>
				</tr>
			</tbody>
		</table>
	</div>
</center>