<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>
<div id="dialog">
<div class="s_shield_table_7">
	<div class="s_shield_table_tr7a">You should not be seeing this. If you are then shame on you.</div>
	<div class="s_shield_table_tr7b"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-trap.png"></div>
	<div class="s_shield_table_tr7d">Wish to prevent errors? Then don't repeat the mistake.</a></div>
</div>
</div>