<div class="s_shield_table_4">
<form action="/shield/vgo" method="POST">
	<div class="s_shield_table_tr4a">Please type the email address you signed up with and click verify to continue.</div>
	<div class="s_shield_table_td4a">CODE:</div>
	<div class="s_shield_table_td4b"><input type="text" name="code" value="<?php echo $this->code; ?>" class="s_shield_form_input4"></div>
	<div class="s_shield_table_td4c">EMAIL:</div>
	<div class="s_shield_table_td4d"><input type="text" name="email" class="s_shield_form_input4"></div>
	<div class="s_shield_table_td4e"><input type="submit" name="submit" value="Verify" class="s_shield_form_submit4"></div>
</form>
</div>