<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
<?php
	if ($this->w0rm == "YAY") {
?>
			<thead>
				<tr>
					<th>Shield => Registration => Success!</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>You may now access to the Sign in page.</td>
				</tr>
<?php
	} else {

?>
			<thead>
				<tr>
					<th>Shield => Registration => Failure</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Something has gone awfully wrong. You should not see this.</td>
				</tr>
<?php } ?>
			</tbody>
		</table>
	</div>
</center>