<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<form action="/staff/lessonsubmit" method="POST">
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Add Lesson</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Curriculum</td>
					<td>
						Pick an appropriate curriculum, you can be part of more than one over time.<br />
						<select name="s_curriculum" class="s_account_form_input0" />
<?php
		$resultA = $this->academyList('curriculum');
		foreach ($resultA as $result) {
			echo "							<option value=\"". $result["id"] ."\">". $result["name"] ."</option>\n";
		}
?>
						</select>
					</td>
				</tr>
				<tr>
					<td>Course</td>
					<td>
						Pick an appropriate course, you can be part of more than one over time.<br />
						<select name="s_course" class="s_account_form_input0" />
<?php
		$resultA = $this->academyList('course');
		foreach ($resultA as $result) {
			echo "							<option value=\"". $result["id"] ."\">". $result["name"] ."</option>\n";
		}
?>
						</select>
					</td>
				</tr>
				<tr>
					<td>Name</td>
					<td>
						(ie: Lesson 1 using cli)<br />
						<input type="text" name="s_name" class="s_account_form_input0" />
					</td>
				</tr>
				<tr>
					<td>Access Level</td>
					<td>
						<select name="s_level" class="s_account_form_input0" />
							<option value="0">Public</option>
							<option value="1">Students</option>
							<option value="2">Staff</option>
							<option value="6">Classified</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td>
						<textarea style="width:800px;height:200px" name="s_other"></textarea>
					</td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" name="submit" value="Add" class="s_account_form_submit0"></td>
				</tr>
			</tbody>
		</table>
	</div>
</form>
</center>