<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
	$my_le    = $this->academyLesson('lookup',$this->stdin);
	$my_co    = $this->academyCourse('lookup',$my_le["cid"]);
	$my_ci    = $this->academyCurriculum('lookup',$my_co["pid"]);
	$owner    = $this->profileInfo($my_le["owner_id"]);
	$state    = $this->academyLesson('status',$this->stdin);
?>


<h1><?php echo $my_le["name"]; ?>
<?php
	if ($this->zempirian->rights >= 3 || $this->zempirian->id == $my_le["owner_id"]) {
?>
	<a href="/staff/editlesson?stdin=<?php echo $my_le["id"]; ?>" class="hack_button">edit</a>
<?php } ?>
</h1>
<br /><br />
Curriculum: <a href="/staff/lookcurriculum?stdin=<?php echo $my_ci["id"]; ?>"><?php echo $my_ci["name"]; ?></a>
<br />
Course: <a href="/staff/lookcourse?stdin=<?php echo $my_co["id"]; ?>"><?php echo $my_co["name"]; ?></a>
<br /><br />
<div><?php echo $my_le["description"]; ?></div>
<div>
<br /><br />
Prerequisites:
<br /><br />
Author: <?php echo $owner["handle"]; ?>, Created: <?php echo $my_le["owner_create"]; ?>, Status: <?php echo $state; ?>

<hr>

