<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_war_table_0">
	<div class="s_war_table_tr0a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_war_table_tr0b">You were unable to sabotage this node.</div>
	<div class="s_war_table_tr0c">
		1. You are not game master<br>
		2. You violated a filter<br>
		3. This node doesn't exist<br>
		4. The option is invalid<br>
	</div>
</div>