<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');

?>

<div class="s_admin_table_0">
<form action="/war/adminaddcampsubmit" method="POST">
	<div class="s_admin_table_td0a">Name:</div>
	<div class="s_admin_table_td0b"><input type="text" name="c_name" class="s_admin_form_input0" /></div>
	<div class="s_admin_table_td0c">Admin:</div>
	<div class="s_admin_table_td0d"><input type="text" name="c_admin" class="s_admin_form_input0" /></div>
	<div class="s_admin_table_tr0a"><input type="submit" name="submit" value="Create Campaign" class="s_admin_form_submit0"></div>
</form>
</div>
