<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_war_table_0">
	<div class="s_war_table_tr0a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_war_table_tr0b">You were unable to change status of Node.</div>
	<div class="s_war_table_tr0c">
		1. You are not game master<br>
		2. You are not admin<br>
		3. You can only promote pending games to active<br>
	</div>
</div>