<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_war_table_0">
	<div class="s_war_table_tr0a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_war_table_tr0b">You are not allowed to unqueue this team.</div>
	<div class="s_war_table_tr0c">
		1. You must be an admin of the campaign<br>
		2. Invalid team<br>
		3. This team and/or campaign is not active<br>
	</div>
</div>