<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
	$node = $this->node;
	$opt  = $this->opt;

?>

Make all changes to your node from here.

<form action="/war/adminsabnodesubmit" method="POST">
<input type="hidden" name="node" value="<?php echo $node; ?>">
<input type="hidden" name="opt"  value="<?php echo $opt; ?>">
<table id="gridb" class="tablesorter">
<thead>
	<tr>
		<th>Name</td>
		<th>Value</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td>Your Message:</td>
		<td><textarea name="c_message" class="s_admin_form_textarea"></textarea></td>
	</tr>

</tbody>
</table>

<input type="submit" name="submit" value="Sabotage" class="s_admin_form_submit0">

</form>
