<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_war_table_0">
	<div class="s_war_table_tr0a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_war_table_tr0b">You are not allowed to report this hack.</div>
	<div class="s_war_table_tr0c">
		1. Invalid choice or password<br>
		2. Box is hacked already<br>
		3. Ummm... Maybe your team owns this?<br>
	</div>
</div>