<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_team_table_3">
	<div class="s_team_table_tr3a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_team_table_tr3b">There was a problem removing the member from the team.</div>
	<div class="s_team_table_tr3c">
		1. You are not team leader<br>
		2. You can not kick yourself<br>
		3. Invalid user
	</div>
</div>