<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_team_table_2">
	<div class="s_team_table_tr2a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_team_table_tr2b">There was a problem adding the email address provided.</div>
	<div class="s_team_table_tr2c">
		1. The email is already on a team<br>
		2. The email is not registered<br>
		3. You are not team leader<br>
	</div>
</div>