<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_mail_table_1">
	<div class="s_mail_table_tr1a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_mail_table_tr1b">You are unable to submit this version.</div>
	<div class="s_mail_table_tr1c">
		1. You already did this<br>
		2. Node is invalid<br>
		3. Option is invalid<br>
		4. You are not allowed<br>
	</div>
</div>