<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_team_table_0">
	<div class="s_team_table_tr0a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_team_table_tr0b">You are not currently part of a team. You will need to create a team or join a team by accepting their invitation.</div>
	<div class="s_team_table_tr0c"><a href="/war/teamcreate" class="hack_button">Create Team</a></div>
</div>