<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
	echo $this->ack;
?>

<div class="s_team_table_4">
	<div class="s_team_table_tr4a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_team_table_tr4b">Your queue request was denied for one of the following reasons.</div>
	<div class="s_team_table_tr4c">
		1. There are no more available nodes at this time<br>
		2. You are already on a campaign<br>
		3. You are not authorized<br>
	</div>
</div>