<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>


<div class="s_account_table_0">
<form action="/war/teamaddsubmit" method="POST">
	<div class="s_account_table_td0c">Member Email:</div>
	<div class="s_account_table_td0d"><input type="text" name="stdin" class="s_account_form_input0" /></div>
	<div class="s_account_table_tr0a">NOTE: The email they signed up with...</div>
	<div class="s_account_table_tr0b"><input type="submit" name="submit" value="Add Member" class="s_account_form_submit0"></div>
</form>
</div>
