<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');

?>

<div class="s_account_table_0">
<form action="/war/teamsubmit" method="POST">
	<div class="s_account_table_td0c">Team Name:</div>
	<div class="s_account_table_td0d"><input type="text" name="stdin" class="s_account_form_input0" /></div>
	<div class="s_account_table_tr0a">Only characters allowed are:<br>a-z A-Z 0-9<br>alphanumeric<br>(no special chars)</div>
	<div class="s_account_table_tr0b"><input type="submit" name="submit" value="Create Team" class="s_account_form_submit0"></div>
</form>
</div>
