<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_war_table_0">
	<div class="s_war_table_tr0a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_war_table_tr0b">You are not allowed to view the war board for one of the following reasons:</div>
	<div class="s_war_table_tr0c">
		1. You must be on a team<br>
		2. Your team has not been queued to play<br>
		3. All your nodes are breached<br>
	</div>
</div>