<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');

	if ($this->approll == "YAY") {
?>

<center>
<form action="/enroll/appsubmit" method="POST">

	<div class="jhjk_table_2">
		<div class="jhjk_td_4">
			<div class="x_title"><h2>Personal</h2></div>
			<div class="b_text">Age: <input type="text" name="age" class="s_enroll_input"></div>
			<div class="b_text">Timezone: <input type="text" name="timezone" class="s_enroll_input"></div>
			<div class="b_text">Gender: <input type="text" name="gender" class="s_enroll_input"></div>
		</div>
		<div class="jhjk_td_5">
			<div class="x_title"><h2>Contact</h2></div>
			<div class="b_text">Reddit: <input type="text" name="reddit" class="s_enroll_input"></div>
			<div class="b_text">IRC: <input type="text" name="irc" class="s_enroll_input"></div>
			<div class="b_text">Email: <input type="text" name="email" class="s_enroll_input"></div>
		</div>
		<div class="jhjk_td_6">
			<div class="x_title"><h2>Position</h2></div>
			<div class="b_text">
				<input type="radio" name="path" value="student">Student</input>
				<input type="radio" name="path" value="teacher">Teacher</input>
				<input type="radio" name="path" value="admin">Administrator</input>
				<input type="radio" name="path" value="dev">Developer</input>
				<input type="radio" name="path" value="writer">Writer</input>
				<input type="radio" name="path" value="artist">Artist</input>
			</div>
		</div>
	</div>

	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="b_title"><h3>Resume, Information, Skillset or other Detailed Information</h3></div>
			<div class="b_text"><textarea style="width:800px;height:200px" name="details"></textarea></div>
		</div>
		<div class="jhjk_tr_1">
			<input type="submit" name="submit" value="SUBMIT APPLICATION">
		</div>
	</div>


</form>
</center>

<?php
	}
	else {
?>

<center>
	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="b_title"><h3>Application Enrollment - CLOSED</h3></div>
			<div class="b_text">Unfornately, you have already enrolled. Please wait for a member of staff to process the application. Thank you!</div>
		</div>
	</div>
</center>

<?php
	}
?>