<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');

	if ($this->approll == "YAY") {
?>

<center>
<form action="/enroll/appsubmit" method="POST">

	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="x_title"><h2>Information</h2></div>
			<div class="b_text">
				Thank you for considering to help the community. Please note that by signing up to participate at a higher level WILL NOT EFFECT your student abilities. Regardless of being part of the Staff at some level, you may still participate in classworks. Thank you for your consideration!
			</div>
		</div>
	</div>

	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="x_title"><h2>Position</h2></div>
			<div class="b_text">
				<input type="radio" name="path" value="teacher">Teacher</input>
				<input type="radio" name="path" value="admin">IRC Admin</input>
				<input type="radio" name="path" value="dev">Developer</input>
				<input type="radio" name="path" value="writer">Writer</input>
				<input type="radio" name="path" value="artist">Artist</input>
				<input type="radio" name="path" value="artist">Wargame Admin</input>
			</div>
		</div>
	</div>

	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="b_title"><h3>Resume, Information, Skillset or other Detailed Information</h3></div>
			<div class="b_text"><textarea style="width:800px;height:200px" name="details"></textarea></div>
			<div class="b_title"><h3>*** Please update your profile first, majority of the skillsets from there will be considered over this form!</h3></div>
		</div>
		<div class="jhjk_tr_1">
			<input type="submit" name="submit" value="SUBMIT APPLICATION">
		</div>
	</div>


</form>
</center>

<?php
	}
	else {
?>

<center>
	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="b_title"><h3>Application Enrollment - CLOSED</h3></div>
			<div class="b_text">Unfornately, you have already enrolled. Please wait for a member of staff to process the application. Thank you!</div>
		</div>
	</div>
</center>

<?php
	}
?>