<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
	<div class="jhjk_table_2">
		<div class="jhjk_td_4">
			<div class="x_title"><h2>Personal</h2></div>
			<div class="b_text">Age: <input type="text"></div>
			<div class="b_text">Timezone: <input type="text"></div>
			<div class="b_text">Gender: <input type="text"></div>
		</div>
		<div class="jhjk_td_5">
			<div class="x_title"><h2>Contact</h2></div>
			<div class="b_text">Reddit: <input type="text"></div>
			<div class="b_text">IRC: <input type="text"></div>
			<div class="b_text">Email: <input type="text"></div>
		</div>
		<div class="jhjk_td_6">
			<div class="x_title"><h2>Position</h2></div>
			<div class="b_text">
				<input type="radio" name="path" value="1">Student</input>
				<input type="radio" name="path" value="2">Teacher</input>
				<input type="radio" name="path" value="3">Administrator</input>
				<input type="radio" name="path" value="4">Developer</input>
				<input type="radio" name="path" value="5">Writer</input>
				<input type="radio" name="path" value="6">Artist</input>
			</div>
		</div>
	</div>

	<div class="jhjk_table_3">
		<div class="jhjk_tr_1">
			<div class="b_title"><h3>Resume, Information, Skillset or other Detailed Information</h3></div>
			<div class="b_text"><textarea style="width:800px;height:200px"></textarea></div>
		</div>
	</div>
</center>