<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<div class="z_about_table_1">
		<div class="z_about_table_tdgap"></div>
		<div class="z_about_table_td0a">Passion in code. Security with love. You're welcome ;)</div>
		<div class="z_about_table_tdgap"></div>
		<div class="z_about_table_td0b">
<em>"In order to achieve perfection in code. Every weakness must be found and reinforced." -- UberLame</em><br><br>
Keeping code clean is always a number one priority.<br><br>
The next important step is beta testing. This is where the true concept of hacking is born. At this point finding: errors, bugs, glitches, etc; are only the stepping stone to the most important and yet the most forgotten practice.<br><br>
Exploitation.<br><br>
It is up to developers to protect the code by preventing exploits. However, this is not a common practice to production developers. That leads to the inevitable outcome of one thing.<br><br>
Hacking.<br><br>
This is when a developer leaves behind a simple issue and it escalates in to access with root privileges. That is why, "Access is God" in the digital world. Delaying to fix such issues will only increase the risk of vulnerable users becoming targets of attacks.<br><br>
The Academy was designed to help educate users through: proof of concepts, hands on training and by the community.<br><br>
</div>
</center>