<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
	<div class="jhjk_table_2">
		<div class="jhjk_td_4">
			<div class="x_title">About</div>
			<div class="x_text">Academy</div>
			<div class="x_text">Read more >></div>
		</div>
		<div class="jhjk_td_5">
			<div class="x_title">Training</div>
			<div class="x_text">Even you do not wish to participate in joining the Academy, you are more than welcome to try all of our online public labs for hacking purposes.</div>
			<div class="x_text">Read more >></div>
		</div>
		<div class="jhjk_td_6">
			<div class="x_title">Participate</div>
			<div class="x_text">Get in touch with <a href="#">community</a> and discuss the Academy with other users and staff.</div>
			<div class="x_text">Read more >></div>
		</div>
	</div>
</center>