<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
	<div class="jhjk_table_2">
		<div class="jhjk_td_4">
			<div class="x_title"><h2>About</h2></div>
			<div class="x_text">Learn about what Zempirians are and why we are focusing on the 'HowToHack Academy' for the community.</div>
		</div>
		<div class="jhjk_td_5">
			<div class="x_title"><h2>Training</h2></div>
			<div class="x_text">Even IF you do not wish to participate in joining the Academy; you are more than welcome to try all of our online public labs for hacking purposes.</div>
		</div>
		<div class="jhjk_td_6">
			<div class="x_title"><h2>Participate</h2></div>
			<div class="x_text">Zempirians' is a community effort. The only reason of it's growth and popularity is the people using it and contributing to it. Get in touch with the staff and with the users now!</div>
		</div>
	</div>
	<div class="jhjk_table_2">
		<div class="jhjk_td_4">
			<div class="x_text"><a href="/about/academy">Read more >></a></div>
		</div>
		<div class="jhjk_td_5">
			<div class="x_text"><a href="/labs/training">Read more >></a></div>
		</div>
		<div class="jhjk_td_6">
			<div class="x_text"><a href="/chat/howtohack">Read more >></a></div>
		</div>
	</div>
</center>