<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<center>
<div class="z_about_table_1">
		<div class="z_about_table_tdgap"></div>
		<div class="z_about_table_td0a">Hacker. War. Games.</div>
		<div class="z_about_table_tdgap"></div>
		<div class="z_about_table_td0b">

<strong>How to join...</strong><br><br>
First, you create an account and use the login system. Once logged in, you will be able to access your control panel for the wargames.<br><br>

<strong>How to start...</strong><br><br>
You can either be invited to a team, in this case you will receive a message in your control panel. Otherwise you can create your own team and invite other members to it.<br><br>

<strong>How to setup...</strong><br><br>
Once you have established a team and confirm you are ready to begin, you will receive login credentials for your server. Log in to the server and setup everything that is outlined in the specific wargame rules (which is available from your control panel).<br><br>

<strong>How to play...</strong><br><br>
After you finish setting up your server and confirm you are ready to battle, you will receive a detailed war report of the current enemies and will be given their ips. You do what you have to from there to hack them.<br><br>
		</div>
		<div class="z_about_table_tdgap"></div>
		<div class="z_about_table_td0b">
** The control panel is located at <a href="http://sploit.me.uk">http://www.sploit.me.uk</a><br><br>
		</div>
		<div class="z_about_table_tdgap"></div>
</div>
</center>