<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
	$skills   = $this->profileSkills('0',$this->stdin);
	$creds    = $this->profileSkills('1',$this->stdin);
	$exps     = $this->profileSkills('2',$this->stdin);
	$intrs    = $this->profileSkills('3',$this->stdin);
	$info     = $this->profileInfo($this->stdin);
?>

<center>
	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Profile: <?php echo $info["handle"]; ?></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Since</td>
					<td><?php echo $info["since"]; ?></td>
				</tr>
				<tr>
					<td>Points</td>
					<td><?php echo $info["points"]; ?></td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="2">Skills</th>
				</tr>
			</thead>
			<tbody>
<?php

	foreach ($skills as $skill) {
?>
				<tr>
					<td><?php echo $skill["skill"]; ?></td>
					<td><?php echo $skill["years"]; ?></td>
				</tr>
<?php
	}
?>

			</tbody>
		</table>

	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="3">Credentials</th>
				</tr>
			</thead>
			<tbody>
<?php

	foreach ($creds as $cred) {
?>
				<tr>
					<td><?php echo $cred["skill"]; ?></td>
					<td><?php echo $cred["years"]; ?></td>
					<td><?php echo $cred["other"]; ?></td>
				</tr>
<?php
	}
?>

			</tbody>
		</table>
	</div>

	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="3">Experience</th>
				</tr>
			</thead>
			<tbody>
<?php

	foreach ($exps as $exp) {
?>
				<tr>
					<td><?php echo $exp["skill"]; ?></td>
					<td><?php echo $exp["years"]; ?></td>
					<td><?php echo $exp["other"]; ?></td>
				</tr>
<?php
	}
?>

			</tbody>
		</table>
	</div>

	<div class="jhjk_table_3">
		<table id="grida" class="tablesorter">
			<thead>
				<tr>
					<th colspan="3">Interests</th>
				</tr>
			</thead>
			<tbody>
<?php

	foreach ($intrs as $intr) {
?>
				<tr>
					<td><?php echo $intr["skill"]; ?></td>
					<td><?php echo $intr["years"]; ?></td>
					<td><?php echo $intr["other"]; ?></td>
				</tr>
<?php
	}
?>
			</tbody>
		</table>
	</div>
</center>