<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>


<table id="grida" class="tablesorter">
<thead>
	<tr>
		<th>Owner</th>
		<th>Title</th>
		<th>Description</th>
		<th>Created</th>
		<th>Archive</th>
		<th>Options</th>
	</tr>
</thead>
<tbody>
<?php
		$resultB = $this->newlist;
		foreach ($resultB as $result) {
			$info = $this->profileInfo($result["gid"]);
?>
	<tr>
		<td><a href="/profile/member/?stdin=<?php echo $result["gid"]; ?>"><?php echo $info["handle"]; ?></a></td>
		<td><?php echo $result["title"]; ?></td>
		<td><?php echo $result["desc"]; ?></td>
		<td><?php echo $result["created"]; ?></td>
		<td><a href="/archives/<?php echo $result["gid"] ."_". $result["id"] .".". $result["type"]; ?>" class="hack_button">View</a></td>
		<td><a href="/mail/compose/?stdin=<?php echo $result["gid"]; ?>" class="hack_button">Message</a></td>
	</tr>
<?php
		}
?>
</tbody>
</table>

</div>
