<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>


<table id="grida" class="tablesorter">
<thead>
	<tr>
		<th>Course</th>
		<th>Created</th>
		<th>Owner</th>
		<th colspan=3>Options</th>
		<th>Status</th>
	</tr>
</thead>
<tbody>
<?php
		$resultB = $this->newlist;
		foreach ($resultB as $result) {
			$info = $this->profileInfo($result["owner_id"]);
?>
	<tr>
		<td><?php echo $result["name"]; ?></td>
		<td><?php echo $result["owner_create"]; ?></td>
		<td><a href="/profile/member/?stdin=<?php echo $result["owner_id"]; ?>"><?php echo $info["handle"]; ?></a></td>
		<td><a href="/mail/compose/?stdin=<?php echo $result["owner_id"]; ?>" class="hack_button">Message</a></td>
		<td><a href="/admin/courseaccept/?stdin=<?php echo $result["id"]; ?>" class="hack_button">Accept</a></td>
		<td><a href="/admin/coursedeny/?stdin=<?php echo $result["id"]; ?>" class="hack_button">Deny</a></td>
		<td><?php if ($result["admin_id"] == "0") { echo "Pending"; } else { if ($result["en"] == "0") { echo "Denied"; } else { echo "Approved"; } } ?></td>
	</tr>
<?php
		}
?>
</tbody>
</table>

</div>
