<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>


<table id="grida" class="tablesorter">
<thead>
	<tr>
		<th>Handle</th>
		<th>Position</th>
		<th>Details</th>
		<th>Submitted</th>
		<th>Options</th>
	</tr>
</thead>
<tbody>
<?php
		$resultB = $this->newlist;
		foreach ($resultB as $result) {
			$info = $this->profileInfo($result["gid"]);
?>
	<tr>
		<td><a href="/profile/member/?stdin=<?php echo $result["gid"]; ?>"><?php echo $info["handle"]; ?></a></td>
		<td><?php echo $result["position"]; ?></td>
		<td><?php echo $result["details"]; ?></td>
		<td><?php echo $result["create"]; ?></td>
		<td><a href="/mail/compose/?stdin=<?php echo $result["gid"]; ?>" class="hack_button">Message</a></td>
	</tr>
<?php
		}
?>
</tbody>
</table>

</div>
