<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<div class="s_mail_table_1">
	<div class="s_mail_table_tr1a"><img src="<?php echo $wmf_xs->dirtheme; ?>/img/shield-warning.png"></div>
	<div class="s_mail_table_tr1b">You are unable to reply to this message.</div>
	<div class="s_mail_table_tr1c">
		1. Message does not exist<br>
		2. Message does not belong to you<br>
		3. Message injection attempt<br>
	</div>
</div>