<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
?>

<ul id="adminMenu">
	<li><a href="javascript:void(0);">Staff Enrollments (<?php echo $this->adminEnroll("total"); ?>)</a>
		<ul>
			<li><a href="/admin/newapps">New (<?php echo $this->adminEnroll("0"); ?>)</a></li>
			<li><a href="/admin/acceptapps">Accepted (<?php echo $this->adminEnroll("1"); ?>)</a></li>
			<li><a href="/admin/refuseapps">Refused (<?php echo $this->adminEnroll("2"); ?>)</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);">Academy Curriculums (<?php echo $this->adminAcademy('curriculumtotal'); ?>)</a>
		<ul>
			<li><a href="/admin/curriculum">View</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);">Academy Courses (<?php echo $this->adminAcademy('coursetotal'); ?>)</a>
		<ul>
			<li><a href="/admin/course">View</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);">Academy Lessons (<?php echo $this->adminAcademy('lessontotal'); ?>)</a>
		<ul>
			<li><a href="/admin/lesson">View</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);">Academy Archives (<?php echo $this->adminArchive('total'); ?>)</a>
		<ul>
			<li><a href="/admin/archivelist/?stdin=1">ACTIVE (<?php echo $this->adminArchive('all'); ?>)</a></li>
			<li><a href="/admin/archivelist/?stdin=0">DELETED (<?php echo $this->adminArchive('dead'); ?>)</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);">Profiles (<?php echo $this->adminProfile('total'); ?>)</a>
		<ul>
			<li><a href="/admin/profilelist/?stdin=1">Artists (<?php echo $this->adminProfile('artist'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=2">Developers (<?php echo $this->adminProfile('developer'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=3">Directors (<?php echo $this->adminProfile('director'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=4">Founders (<?php echo $this->adminProfile('founder'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=5">IRC Admins (<?php echo $this->adminProfile('irc_admin'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=6">Students (<?php echo $this->adminProfile('student'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=7">Teachers (<?php echo $this->adminProfile('teacher'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=8">Wargame Admins (<?php echo $this->adminProfile('wargame_admin'); ?>)</a></li>
			<li><a href="/admin/profilelist/?stdin=9">Writers (<?php echo $this->adminProfile('writer'); ?>)</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);">Tools</a>
		<ul>
			<li><a href="/admin/emailtool">Email</a></li>
		</ul>
	</li>
</ul>
