<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
	$mytheme = 0;
	$wmf_xs->theme = 0;
	$wmf_xs->dirtheme = "/sthemes/0";
?>

<!DOCTYPE html> 
<html>
<head>
<title>Zempirians, Zempire Network.</title>
<base href="http://www.zempirians.com/" />
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" /> 
<meta name="Description" content="description, for seo purposes" />
<meta name="Keywords" content="keyword 1, keyword 2" />

<?= $this->partial('core.jscript.phtml'); ?>
<?= $this->partial('core.stylesheets.phtml'); ?>

</head>

<body>

<center>
<?= $this->partial('core.toolbar.phtml'); ?>
</center>
<?= $this->partial('core.james.phtml'); ?>

<div id="jhjk_layout">
		<?= $this->layout()->content; ?>
</div>

<?= $this->partial('core.footer.phtml'); ?>

</body>
</html>