<?php

	$wmf_xs  = new Zend_Session_Namespace('SPLOIT');

?>

<div id="jhjk_footer">
	<center>
	<div class="jhjk_table_1">
		<div class="jhjk_td_1">
			<div class="f_title"><h3>Quick Links</h3></div>
			<div class="f_text"><a href="/archives/list/?stdin=1" class="f_link">Archives</a></div>
			<div class="f_text"><a href="/labs/training" class="f_link">Labs</a></div>
			<div class="f_text"><a href="/about/wargames" class="f_link">Wargames</a></div>
		</div>
		<div class="jhjk_td_2">
			<div class="f_title"><h3>Stay in touch</h3></div>
			<div class="f_text">You can follow us on the following social platforms:</div>
			<div class="f_text"><a href="https://github.com/Zempirians" class="f_link">GitHub</a> , <a href="http://reddit.com/r/HowToHack" class="f_link">Reddit</a> , <a href="/chat/howtohack" class="f_link">IRC</a></div>
		</div>
		<div class="jhjk_td_3">
			<div class="f_title"><h3>Community</h3></div>
			<div class="f_text">Zempirians is a community effort. The only reason of it's growth and popularity is the people using and contributing to it.</div>
		</div>
	</div>
	</center>
</div>
<div id="jhjk_footstat">
		<center>
		<div class="jhjk_stat">
			<?php echo $wmf_xs->stats; ?>
		</div>
		</center>
</div>