<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');

?>
<link rel="stylesheet" type="text/css" href="<?php echo $wmf_xs->dirtheme; ?>/css/template.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $wmf_xs->dirtheme; ?>/css/global.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $wmf_xs->dirtheme; ?>/css/toolbar.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $wmf_xs->dirtheme; ?>/css/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $wmf_xs->dirtheme; ?>/css/jquery-grid.css" />
