<?php

	$wmf_xs  = new Zend_Session_Namespace('SPLOIT');

?>

<div id="jhjk_footer">
	<center>
	<div class="jhjk_table_1">
		<div class="jhjk_td_1">
			<div class="f_title">Quick Links</div>
			<div class="f_text">Academy</div>
			<div class="f_text">Labs</div>
			<div class="f_text">Wargames</div>
		</div>
		<div class="jhjk_td_2">
			<div class="f_title">Stay in touch</div>
			<div class="f_text">You can follow us on the following social platforms:</div>
			<div class="f_text">GitHub | Reddit | IRC</div>
		</div>
		<div class="jhjk_td_3">
			<div class="f_title">Community</div>
			<div class="f_text">Get in touch with <a href="#">community</a> and discuss the Academy with other users and staff.</div>
		</div>
	</div>
	</center>
</div>
<div id="jhjk_footstat">
		<center>
		<div class="jhjk_stat">
			<?php echo $wmf_xs->stats; ?>
		</div>
		</center>
</div>