<?php
	$wmf_xs   = new Zend_Session_Namespace('SPLOIT');
	$mytheme = 0;
	$wmf_xs->theme = 0;
	$wmf_xs->dirtheme = "/sthemes/0";
?>

<!DOCTYPE html> 
<html>
<head>
<title>Zempirians, Zempire Network.</title>
<base href="http://www.zempirians.com/" />
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" /> 
<meta name="Description" content="description, for seo purposes" />
<meta name="Keywords" content="keyword 1, keyword 2" />

<?= $this->partial('staff.jscript.phtml'); ?>
<?= $this->partial('staff.stylesheets.phtml'); ?>

</head>

<body>

<?= $this->partial('staff.toolbar.phtml'); ?>

<div class="jhjk_frame">
	<div class="jhjk_frame_logo"><a href="http://www.zempirians.com"><img src="/sthemes/0/img/logo-sm.png" class="tbar_icon" border="0"></a></div>
</div>

<div id="jhjk_layout">
	<div id="jhjk_template">
		<div class="jhjk_template_l">
<?= $this->partial('staff.sidebar.phtml'); ?>
		</div>
		<div class="jhjk_template_r">
<?= $this->layout()->content; ?>
		</div>
	</div>
</div>

</body>
</html>